#!/bin/bash

# -----------------------------------------------------------------------------
# Auto-Unlock LUKS Encrypted Root Partition at Boot
# -----------------------------------------------------------------------------
# WARNING: This script stores a key file in /boot (unencrypted). Use with caution.
# -----------------------------------------------------------------------------

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Please run as root/sudo"
    exit 1
fi

# ----------------------------------
# Configuration
# ----------------------------------
KEYFILE="/boot/root_crypt.key"  # Key file path
LUKS_DEVICE="/dev/sdX"          # Replace with your LUKS device (e.g., /dev/sda5)

# ----------------------------------
# 1. Create Key File
# ----------------------------------
if [ -f "$KEYFILE" ]; then
    read -p "Key file $KEYFILE exists. Overwrite? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
    rm -f "$KEYFILE"
fi

echo "Generating key file..."
dd if=/dev/urandom of="$KEYFILE" bs=1024 count=4
chmod 0400 "$KEYFILE"

# ----------------------------------
# 2. Add Key to LUKS
# ----------------------------------
echo "Adding key to LUKS device $LUKS_DEVICE..."
cryptsetup luksAddKey "$LUKS_DEVICE" "$KEYFILE"

# ----------------------------------
# 3. Update /etc/crypttab
# ----------------------------------
LUKS_UUID=$(blkid -s UUID -o value "$LUKS_DEVICE")

echo "Updating /etc/crypttab..."
cp /etc/crypttab /etc/crypttab.bak  # Backup
sed -i "/root_crypt/d" /etc/crypttab  # Remove existing entry
echo "root_crypt UUID=$LUKS_UUID $KEYFILE luks" >> /etc/crypttab

# ----------------------------------
# 4. Configure Initramfs Hook
# ----------------------------------
echo "Configuring cryptsetup hook..."
cat > /etc/cryptsetup-initramfs/conf-hook <<EOF
# Auto-generated by unlock script
CRYPTSETUP=y
KEYFILE_PATTERN=/boot/*.key
EOF

# ----------------------------------
# 5. (Optional) Disable Floppy Errors
# ----------------------------------
echo "blacklist floppy" > /etc/modprobe.d/blacklist-floppy.conf

# ----------------------------------
# 6. Rebuild Initramfs
# ----------------------------------
echo "Rebuilding initramfs..."
update-initramfs -u -k all

# ----------------------------------
# Verification
# ----------------------------------
echo -e "\nVerification:"
echo "Key file in initramfs?:"
lsinitramfs /boot/initrd.img-$(uname -r) | grep "$(basename $KEYFILE)"

echo -e "\nDone! Reboot to test."
echo "WARNING: Ensure /boot is secured (physical access/Secure Boot)."
